# generated by genlibbuild
proto_library(
    name = 'meta_proto',
    srcs = 'src/meta.proto'
)
cc_library(
    name = 'ps-lite',
    srcs = [
        'src/customer.cc',
        'src/postoffice.cc',
        'src/van.cc',
    ],
    incs = [
        'include'
    ],
    defs = [
        'DMLC_USE_CXX11',
        'DMLC_USE_GLOG',
        'DMLC_USE_BLADE',
    ],
    deps = [
        ':meta_proto',
        '//thirdparty/zeromq:zmq'
    ]
)

